---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Check if reboot is required
  command: needs-restarting -r
  register: reboot_required
  ignore_errors: True
  changed_when: False

- name: Reboot the server
  reboot:
    post_reboot_delay: 30
  when: reboot_required.rc == 1
